import { Milestone, ArrowDownRight } from 'lucide-react';

interface BridgeRoleLadderProps { path?: Array<{ role?: string; estimatedMonths?: number; salaryRange?: string; keySkillsToAcquire?: string[] }>; matches?: Array<{ role?: string; weeks_to_ready?: number; salary_avg_lpa?: number; is_bridge_role?: boolean }> }

export function BridgeRoleLadder({ path = [], matches = [] }: BridgeRoleLadderProps) {
  const roles = path.length ? path : matches.slice(0, 4).map((match) => ({ role: match.role, estimatedMonths: Math.ceil((match.weeks_to_ready || 8) / 4), salaryRange: match.salary_avg_lpa ? `₹${match.salary_avg_lpa} LPA` : undefined, keySkillsToAcquire: [] }));
  return <section className="rounded-3xl border-2 border-hairline bg-surface-card p-6 shadow-sm"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.16em] text-brand-teal"><Milestone className="h-4 w-4" /> Path engine</div><h2 className="mt-2 font-display text-2xl font-semibold tracking-tight text-ink">Bridge Role Ladder</h2><p className="mt-1 text-sm leading-6 text-muted">The smallest credible steps between where you are and where you want to go.</p><div className="mt-5 space-y-3">{(roles.length ? roles : [{ role: 'First bridge role', estimatedMonths: 2, salaryRange: 'Calibrate after intake', keySkillsToAcquire: ['Confirm your target'] }]).map((item, index) => <div key={`${item.role}-${index}`} className="relative flex gap-3 rounded-2xl border border-hairline bg-surface-soft p-4"><div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-brand-teal text-xs font-bold text-white">{index + 1}</div><div className="min-w-0"><p className="font-semibold text-ink">{item.role || 'Bridge role'}</p><p className="mt-1 text-xs text-muted">{item.estimatedMonths ? `${item.estimatedMonths} months to prepare` : 'Timeline to be confirmed'}{item.salaryRange ? ` · ${item.salaryRange}` : ''}</p>{item.keySkillsToAcquire?.length ? <p className="mt-2 text-xs text-brand-teal">Next proof: {item.keySkillsToAcquire.slice(0, 3).join(', ')}</p> : null}</div>{index < roles.length - 1 ? <ArrowDownRight className="absolute -bottom-4 left-2 h-4 w-4 text-muted" /> : null}</div>)}</div></section>;
}

